---
- name: Launching new hosts
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Provision nodejs node
      local_action: ec2  keypair={{ mykeypair }} instance_type={{ instance_type }} image={{ image }} wait=true zone={{ zone }} region={{ zone[:-1] }} instance_tags='{"name":"{{ item }}"}' wait_timeout=600
      register: ec2
      with_items:      
        - "njs001"
    
    - name: Print new instance details
      debug: var=ec2
    
    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.instances[0]['public_dns_name'] }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.results
    
    - name: Add new instance to host group
      add_host: hostname={{ item.instances[0]['public_ip'] }} groupname=nodejs instance_hostname={{ item.item }} user=ubuntu
      with_items: ec2.results

- name: Updating new instance
  hosts: nodejs
  gather_facts: no
  user: "{{ user }}"
  sudo: yes

  tasks:
    - name: Updating hostname
      hostname: name={{ instance_hostname }}

    - name: Install nodejs, npm
      apt: name={{ item }}
      with_items:
        - nodejs
        - nginx

    - name: Downloading hello-world app
      shell: curl -s https://raw.githubusercontent.com/chetandhembre/hello-world-node/master/main.js > main.js

    - name: Starting nodejs app
      shell: nohup nodejs main.js &

    - name: Updating nginx config
      template: src=templates/nodejs.conf dest=/etc/nginx/conf.d
      notify:
        - reload nginx
  
    - name: Deleting default config file
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - reload nginx

  handlers:
    - name: reload nginx
      service:  name=nginx state=reloaded

